export const HOUSING_KEYWORDS: string[] = [
  "alquiler", "renta", "arriendo", "alquilar", "rentar", "mes", "mensualidad",
  "piso", "apartamento", "estudio", "loft", "atico", "ático", "duplex", "dúplex",
  "casa", "chalet", "vivienda", "habitacion", "habitación", "dormitorio", "cuarto",
  "hipoteca", "prestamo", "préstamo", "cuota", "banco", "hipotecario",
  "comunidad", "gastos comunes", "derrama", "porteria", "portería",
  "luz", "electricidad", "endesa", "iberdrola", "naturgy", "factura", "recibo",
  "consumo", "potencia", "contador", "kwh", "vatio",
  "agua", "fontaneria", "fontanería", "grifo", "calentador", "termo", "ducha",
  "gas", "calefaccion", "calefacción", "caldera", "radiador", "butano", "gasnatural",
  "internet", "fibra", "wifi", "router", "movistar", "vodafone", "orange",
  "digi", "jazztel", "masmovil", "masmóvil", "operador", "datos", "banda ancha",
  "telefono", "telefónica", "móvil", "fijo", "linea", "línea", "tarifa plana",
  "limpieza", "limpiador", "aspiradora", "productos", "detergente", "jabon", "jabón",
  "piscina", "terraza", "balcon", "balcón", "trastero", "sotano", "sótano",
  "mudanza", "mudarse", "fianza", "deposito", "contrato", "inmobiliaria", "agencia",
  "airbnb", "booking", "hotel", "hostal", "albergue", "pension", "pensión",
  "alojamiento", "hospedaje", "acampar", "camping", "glamping", "tienda",
  "mueble", "muebles", "ikea", "decoracion", "decoración", "pintura", "obra",
  "reforma", "reparacion", "reparación", "manitas", "bricolaje", "bricolage",
  "fontanero", "electricista", "cerrajero", "pintor", "albañil",
  "yesero", "carpintero", "parquetista", "tapicero", "cristalero",
  "persianista", "calderista", "gasista", "instalador", "tecnico", "técnico",
  "aire acondicionado", "split", "frio", "frío", "calor", "bomba calor",
  "termo electrico", "termo eléctrico", "calentador gas",
  "averia", "avería", "rotura", "gotera", "humedad", "mancha", "fuga",
  "escape", "atasco", "embozo", "cortocircuito", "salto diferencial",
  "tejado", "cubierta", "fachada", "pared", "techo", "suelo", "moho", "grieta",
  "junta", "presidente", "administrador", "finca", "conserje", "portero",
  "normas", "horario", "ruido", "mascota", "votacion", "votación", "acta",
  "compra", "venta", "traspaso", "cesion", "cesión",
  "aval", "nominativa", "nómina", "solvencia", "referencia", "visita",
  "inventario", "entrada", "salida", "checkin", "check-in", "checkout", "check-out",
  "leroy merlin", "bricomart", "brico depot", "bauhaus", "aki",
  "brocha", "rodillo", "cinta carrocero", "lijar", "lija",
  "masilla", "yeso", "espatula", "espátula", "destornillador", "martillo",
  "taladro", "atornillador", "taco", "tornillo", "alcayata", "clavo",
  "estanteria", "estantería", "balda", "perchero", "cortina", "persiana",
  "estores", "lampara", "lámpara", "bombilla", "led", "halogena", "halógena",
  "placa solar", "aerotermia", "biomasa", "pellet",
  "bono social", "descuento", "ahorro", "eficiencia", "renovable",
  "suministro", "contratacion", "contratación", "alta", "baja", "cambio titular",
  "domiciliacion", "domiciliación", "adeudo", "cobro",
];
