export const LEISURE_KEYWORDS: string[] = [
  "cine", "pelicula", "película", "film", "estreno", "sala", "palomitas",
  "entrada", "entradas", "ticket", "espectaculo", "espectáculo", "taquilla",
  "concierto", "festival", "musica", "música", "banda", "grupo", "cantante", "dj",
  "fiesta", "noche",
  "cumpleaños", "cumple", "celebracion", "celebración", "aniversario",
  "despedida", "bienvenida", "reunion", "reunión", "quedada", "encuentro",
  "teatro", "obra", "musical", "comedia", "drama", "impro", "standup", "monologo",
  "museo", "exposicion", "exposición", "galeria", "galería", "arte", "coleccion",
  "gym", "gimnasio", "fitness", "crossfit", "yoga", "pilates", "spinning", "zumba",
  "deporte", "partido", "futbol", "fútbol", "baloncesto", "tenis", "padel", "pádel",
  "golf", "esquiar", "esqui", "esquí", "snowboard", "surf", "buceo", "natacion",
  "spa", "balneario", "masaje", "sauna", "jacuzzi", "termas", "relax", "bienestar",
  "paseo", "pasear", "andar", "caminata", "correr", "running", "footing",
  "maraton", "maratón", "media maraton", "carrera popular",
  "triatlon", "triatlón", "duatlon", "duatlón", "ironman",
  "boxeo", "mma", "judo", "karate", "taekwondo", "aikido", "jiujitsu", "capoeira",
  "danza", "baile", "salsa", "bachata", "tango", "flamenco", "sevillanas",
  "subscripcion", "suscripción", "spotify", "apple music", "youtube premium",
  "youtube", "twitch", "patreon", "onlyfans", "substack", "medium",
  "audible", "podimo", "ivoox", "podcast", "membresia", "membresía",
  "premium", "plus", "familiar", "duo", "individual", "anual", "mensual",
  "ps5", "ps4", "xbox series", "xbox one", "nintendo switch", "switch oled",
  "steam deck", "pc gaming", "juego", "dlc", "expansion", "expansión",
  "pase batalla", "skins", "moneda virtual", "vbucks", "robux", "fifa points",
  "tablero", "catan", "monopoly", "trivial", "scrabble", "dixit",
  "magic", "pokemon", "pokémon", "yu gi oh", "warhammer", "d&d", "rol",
  "escape room", "room escape", "scape room", "enigma",
  "libreria", "librería", "libro", "novela", "comic", "cómic", "manga",
  "revista", "periodico", "periódico", "prensa",
  "conferencia", "charla", "taller", "curso", "masterclass", "workshop",
  "seminario", "webinar", "formacion", "formación", "aprendizaje",
  "idioma", "clase", "profesor", "academia", "escuela", "universidad",
  "conservatorio", "auditorio", "palacio congresos", "feria",
  "excursion", "excursión", "escapada", "fin de semana", "puente", "vacaciones",
  "viaje", "circuito", "tour", "guia", "guía",
  "agencia viajes", "touroperador", "paquete", "todo incluido", "ida vuelta",
  "reserva", "reservar", "hostal", "hostel", "cabaña", "refugio", "parador",
  "casa rural", "turismo rural",
  "monumento", "catedral", "iglesia", "castillo", "alcazaba", "palacio",
  "ruina", "yacimiento", "templo", "mezquita", "sinagoga",
  "peluqueria", "peluquería", "barberia", "barbería", "corte pelo",
  "tinte", "mechas", "manicura", "pedicura", "uñas", "depilacion", "depilación",
  "laser", "láser", "cera", "hilo", "cejas", "pestañas",
  "masaje", "quiromasaje", "drenaje", "fisioterapia", "osteopatia", "osteopatía",
  "quiropractico", "quiropráctico", "acupuntura",
  "meditacion", "meditación", "mindfulness", "retiro", "terapia",
  "psicologo", "psicólogo", "coach", "coaching",
  "netflix", "hbo", "prime video", "disney plus", "streaming",
  "apuesta", "lotería", "loteria", "once", "primitiva", "euromillon", "euromillón",
  "cigarro", "tabaco", "estanco", "liar", "vapear", "vaporizador",
  "zoo", "acuario", "parque tematico", "parque de atracciones", "disney", "portaventura",
  "piscina", "playa", "mar", "montaña", "parque",
  "juego", "videojuego", "consola", "playstation", "xbox", "nintendo",
  "steam", "arcade", "maquina", "pinball", "billar", "futbolin",
  "bolera", "bolos", "laser tag", "paintball",
];
