export const SHOPPING_KEYWORDS: string[] = [
  "compra", "compras", "comprar", "tienda", "centro comercial", "outlet", "mall",
  "supermercado", "super", "mercadona", "carrefour", "lidl", "aldi", "eroski", "alcampo",
  "dia", "consum", "ahorramas", "hipercor", "el corte ingles", "el corte inglés",
  "ropa", "vestir", "camiseta", "pantalon", "pantalón", "zapatos", "zapatillas",
  "chaqueta", "abrigo", "jersey", "sudadera", "vestido", "falda", "traje", "corbata",
  "lenceria", "lencería", "pijama", "bata", "gorra", "sombrero", "bufanda", "guantes",
  "zara", "hm", "h&m", "bershka", "pullandbear", "mango", "primark", "stradivarius",
  "massimo dutti", "oysho", "lefties", "uniqlo", "cortefiel", "springfield",
  "calzado", "deportivas", "botas", "sandalias", "tacon", "tacón", "mocasines",
  "electronica", "electrónica", "movil", "móvil", "telefono", "smartphone", "iphone",
  "samsung", "xiaomi", "tablet", "ipad", "portatil", "laptop", "ordenador", "pc",
  "auriculares", "cascos", "airpods", "altavoz", "bluetooth", "cable", "cargador",
  "funda", "protector", "pantalla", "cristal templado",
  "hogar", "deco", "decoracion", "ikea", "zara home", "casa", "sabanas",
  "sábanas", "almohada", "toalla", "cocina", "menaje", "olla", "plato", "vaso",
  "cubierto", "cuberteria", "cubertería",
  "juguete", "niño", "peluche", "lego", "puzzle", "juego mesa", "carta",
  "libro", "libreria", "librería", "amazon", "kindle", "ebook", "lectura",
  "farmacia", "medicamento", "parafarmacia", "crema", "cosmetica", "cosmética",
  "maquillaje", "perfume", "colonia", "desodorante", "champu", "champú", "gel",
  "papeleria", "papelería", "boligrafo", "bolígrafo", "cuaderno", "agenda", "oficina",
  "ferreteria", "ferretería", "herramienta", "tornillo", "pintura", "brocha",
  "jardin", "jardín", "planta", "maceta", "tierra", "semilla", "flor", "floristeria",
  "mascota", "perro", "gato", "comida animal", "pienso", "veterinario", "arena",
  "segunda mano", "wallapop", "vinted", "ebay", "mercadillo", "rastro", "trueque",
  "regalo", "detalle", "navidad", "reyes", "san valentin", "día de", "amigo invisible",
];
