export const TRANSPORT_KEYWORDS: string[] = [
  "taxi", "uber", "cabify", "bolt", "free now", "freenow", "coche", "viaje",
  "trayecto", "carrera", "tarifa", "conductor", "uberx", "uberxl", "comfort", "black",
  "bus", "autobus", "autobús", "autocar", "guagua", "colectivo", "micro",
  "tren", "ave", "cercanias", "cercanías", "renfe", "rail", "ferrocarril",
  "metro", "subte", "subterraneo", "tranvia", "tranvía",
  "bicicleta", "bici", "patinete", "moto", "scooter", "vespa", "ciclomotor",
  "combustible", "gasolina", "diesel", "gasóleo", "cargar", "electrica",
  "eléctrico", "enchufe", "gasolinera", "repostar", "deposito", "depósito",
  "peaje", "autopista", "parking", "aparcamiento", "garaje", "estacionamiento",
  "parquimetro", "parquímetro", "zona azul", "zona verde",
  "avion", "avión", "vuelo", "aeropuerto", "ryanair", "vueling", "iberia",
  "air europa", "maleta", "equipaje", "facturar", "embarque", "despegar",
  "barco", "ferry", "transbordador", "puerto", "crucero", "naviera",
  "autocaravana", "camper", "furgoneta", "alquiler", "renting", "rent a car",
  "billete", "ticket", "bono", "abono", "tarjeta transporte",
  "andando", "caminando", "a pie", "ruta", "camino", "senderismo", "trekking",
  "seguro", "poliza", "póliza", "itv", "revision", "revisión", "mantenimiento",
  "aceite", "rueda", "neumatico", "neumático", "michelin", "bridgestone",
  "cambio", "filtro", "bateria", "batería", "bujia", "bujía", "correa",
  "freno", "pastilla", "disco", "embrague", "amortiguador",
  "tubo", "silenciador", "catalizador", "inyector", "turbo", "radiador",
  "anticongelante", "refrigerante", "limpiaparabrisas", "escobilla",
  "lavado", "lavadero", "taller", "mecanico", "mecánico", "chapa", "pintura",
  "concesionario", "carnet", "carné", "permiso", "puntos", "multa",
  "radar", "dgt", "trafico", "tráfico", "ora", "grua", "grúa", "cepo",
  "casco", "cadena", "piñon", "piñón", "plato", "pedal", "manillar",
  "sillin", "sillín", "candado", "antirrobo", "decathlon", "bicimad", "bicing",
  "carrera minima", "carrera mínima", "suplemento", "maletero", "propina",
  "viaje compartido", "carpool", "blablacar",
  "envío", "mensajeria", "mensajería", "correos", "seur", "mrw", "dhl", "fedex",
  "ups", "paquete", "paqueteria", "paquetería",
  "ouigo", "iryo", "sncf", "eurostar", "thalys", "tgv", "talgo", "alvia",
  "euromed", "billete tren", "billete avion",
];
